### ISSUE TITLE
Investigate signal diffusion acceleration tools

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/Emergence#1]
PDE approximation with operator learning: https://www.quantamagazine.org/new-neural-networks-solve-hardest-equations-faster-than-ever-20210419/

**Comment by TimJentzsch** [comment]
What about a simple blurring technique? We could store the signal strengths in an image texture and then just blur it in a shader every X seconds.
We'd have to see which blurring technique to use for it to make sense with hex coordinates, but I assume that could be performant enough.

See also [this video](https://youtu.be/X-iSQQgOd1A?t=776) where a technique like this was used for slime simulation.

**Comment by alice-i-cecile** [comment]
For blurring, I would be worried that the signals wouldn't respect walls or other obstructions, which leads to very poor pathfinding behavior.

**Comment by bzm3r** [comment]
> What about a simple blurring technique? We could store the signal strengths in an image texture and then just blur it in a shader every X seconds. We'd have to see which blurring technique to use for it to make sense with hex coordinates, but I assume that could be performant enough.
> 
> See also [this video](https://youtu.be/X-iSQQgOd1A?t=776) where a technique like this was used for slime simulation.

How would we get the data back from the GPU? Typically, reading data back from the GPU is not cheap.

**Comment by TimJentzsch** [comment]
> > What about a simple blurring technique? We could store the signal strengths in an image texture and then just blur it in a shader every X seconds. We'd have to see which blurring technique to use for it to make sense with hex coordinates, but I assume that could be performant enough.
> > See also [this video](https://youtu.be/X-iSQQgOd1A?t=776) where a technique like this was used for slime simulation.
> 
> How would we get the data back from the GPU? Typically, reading data back from the GPU is not cheap.

We'd have to send the texture to the GPU, process it there and then send the modified texture back to the CPU.
I assume at a certain size this will be faster because of the faster processing time, but we'd need to benchmark it to know for sure
