### ISSUE TITLE
Allow for debug UI to be toggled on/off

### ISSUE THREAD

**Issue by wallamide** [Leafwing-Studios/Emergence#100]
Currently the debug UI is always on. There is commented code in `debug_ui.rs` and `lib.rs` for debug_tools that can be extended to allow for the UI to be toggled and the code will need to be worked on later.

**Comment by bencecile** [comment]
This issue is now fixed from #171.

**Comment by TimJentzsch** [comment]
@bencecile As a tip, when you add "Closes #171" or "Fixes #171" in the PR description, the issue will be closed automatically once the PR has been merged :)
