### ISSUE TITLE
Move FrameDiagnosticPlugin to a cargo feature.

### ISSUE THREAD

**Issue by wallamide** [Leafwing-Studios/Emergence#101]
`emergence_lib/src/graphics/mod.rs` adds `FrameTimeDiagnosticsPlugin` as a plugin and not a bevy feature. This can be fixed in a later PR.

**Comment by bzm3r** [comment]
This was completed as part of moving things to debug tools: https://github.com/Leafwing-Studios/Emergence/blob/8d5fd992217631f09c7f99d0165c3e84ca609eae/tools/debug_tools/src/lib.rs#L93
