### ISSUE TITLE
Support tracing for performance measurement

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#105]
See: https://bevy-cheatbook.github.io/setup/bevy-config.html?highlight=tracing#tracing

Much more information here: https://github.com/bevyengine/bevy/blob/main/docs/profiling.md

Work we have to do from our end:

- [ ] create a PowerShell script that runs the program in release mode, and produces tracy traces from Chrome traces
- [ ] create specific "run modes" for the main program to help with performance testing of specific things (e.g. simulation only, or simulation + graphics, or simulation + graphics + interaction)

**Comment by bzm3r** [comment]
Tasks:

- [ ] Create a performance measurement cargo profile

**Comment by alice-i-cecile** [comment]
The basic setup is good enough for now: I ran the traces through tracing-chrome today and was quite happy with the workflow.
