### ISSUE TITLE
Determine the UI for modifying organisms

### ISSUE THREAD

**Issue by wallamide** [Leafwing-Studios/Emergence#106]
As the UI gets added into the game, we will need to consider how we want to allow the player to modify organisms. Currently, we have planned for a discrete tradeoff between related choices model where the player will be able to select one modification/upgrade per tier from the upgrade tree. The current plan is to implement something like WoW's older PvP Talent screen where the user has a tiered list of options, with each tier corresponding to the level you unlock the talent. This issue will be updated with a sketch up soon.

**Comment by alice-i-cecile** [comment]
Closing for now: needs more design work first.
