### ISSUE TITLE
Create and use `Passability` enum with variants `Passable` and `Impassable` in `simulation/pathfinding.rs`

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#107]
This will help to improve code readability

Initially the thought was to simply a provide a constant for the two passability cases
```
const PASSABLE: bool = true;
const IMPASSABLE: bool = false;
```

but perhaps an enum might work better:

```
pub enum Passability {
    Passable,
    Impassable,
}
```

**Comment by TimJentzsch** [comment]
An enum might also work in this case :)

**Comment by bzm3r** [comment]
> An enum might also work in this case :)

Yeah, might work better actually.

**Comment by TimJentzsch** [comment]
Ah, but we can't pass them to `MapFilter::new_with_default`, so maybe it doesn't work after all :D

**Comment by bzm3r** [comment]
> Ah, but we can't pass them to `MapFilter::new_with_default`, so maybe it doesn't work after all :D

No, I think we can! Because I will just change `MapFilter` to be more generic :)

**Comment by wallamide** [comment]
we will want to generalize how this enum is used so that each unit will know if the terrain is impassible to them.

**Comment by alice-i-cecile** [comment]
Closing out: this is being rearchitected.
