### ISSUE TITLE
Use bevy_pancam with leafwing-input-manager for camera controller

### ISSUE THREAD

**Issue by wallamide** [Leafwing-Studios/Emergence#113]
`camera.rs` needs to have `bevy_pancam` run through `leafwing-input-manager`. This will allow us to use `bevy-inspector-egui` more easily as mentioned in #112 and uses one crate for input management.

**Comment by alice-i-cecile** [comment]
My opinion here is that we should just "vendor" the pancam code. Incorporate it directly into our own code base, with credit at the top of that file.
