### ISSUE TITLE
Add more docs to `GRID_SIZE` in `generation.rs`

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#123]
Explain where the values come from, what ratio `x` and `y` should have (approximately) and the relation to the `TILE_SIZE` in `graphics/organisms.rs`.

**Comment by bzm3r** [comment]
Actually, this pointed to a deeper issue: `GRID_SIZE` being in `generation.rs` is a relic of the pre-graphics/simulation separation era.
