### ISSUE TITLE
Simplify startup system setup in `GenerationPlugin`

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#125]
We probably need stageless for this, but it would be nice to simplify this setup of having a chain of multiple systems after one another:
<https://github.com/Leafwing-Studios/Emergence/blob/4988fb63ad71354d5d1898b478b1b76253ed8d0a/emergence_lib/src/simulation/generation.rs#L105-L125>

**Comment by bzm3r** [comment]
This is blocked on stageless I think. I don't know what the right issue to link to is though.

**Comment by alice-i-cecile** [comment]
This is substantially better now, closing out :)
