### ISSUE TITLE
Ensure permissively licensed dependencies using `cargo-deny`

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/Emergence#128]
We cannot include GPL or closed source code in an MIT project.

Enforce this using https://github.com/EmbarkStudios/cargo-deny

**Comment by TimJentzsch** [comment]
@alice-i-cecile Do you also want checks for security advisories, duplicate dependencies and all that?

**Comment by alice-i-cecile** [comment]
Yes please!
