### ISSUE TITLE
Check if we can batch component insertions in `TerrainType::instantiate`

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#131]
I think a single `bundle.insert` call (e.g. with a tuple of bundles) is more efficient than multiple `insert` calls with single bundles.
We should check if we can batch those insert calls here.

<https://github.com/Leafwing-Studios/Emergence/blob/1b2025ddb4f7fd09a637878b2fa296b4c8b19383/emergence_lib/src/terrain/mod.rs#L33-L51>

**Comment by alice-i-cecile** [comment]
Yes, it is.

**Comment by alice-i-cecile** [comment]
No longer relevant.
