### ISSUE TITLE
Add loaders to genre mechanics and glossary

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/Emergence#161]
These load items directly from belts into storage and assemblers.

**Comment by bzm3r** [comment]
Is this the same as ["inserter"](https://github.com/Leafwing-Studios/Emergence/blob/main/design/src/glossary.md#inserter)? In this case, we can close this issue. 

Or we can add that "loader" is an alternative term in the definition for "inserter" (that way it can be found via CTRL+F).

**Comment by alice-i-cecile** [comment]
Nope, they're different! https://www.reddit.com/r/factorio/comments/4z7di5/quick_question_what_is_a_loader/
