### ISSUE TITLE
Document technical and organisational risks

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#163]
I'm not sure if this fits in the design book or should be somewhere else, but it will be useful to keep track of the most dangerous risks we are going to face during development.
I assume a couple will be caused by the open source and indie nature of this project, but some might be generally applicable to game development.

Keeping track of these explicitly will help us to mitigate or even eliminate some of the risks.

**Comment by alice-i-cecile** [comment]
Agreed that this should exist! We can stick it in the design book for now, and then reorganize when we have a better idea of the structure.
