### ISSUE TITLE
Add genre analysis of control schemes to design book

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#174]
The control scheme is a very important factor for the user experience and should be taken into consideration when designing features.
It's often challenging for complex games like factory builders and RTS games, as they have many actions to execute which should have shortcuts available.

I think it makes sense to look at both factory builders and RTS games to take inspiration.
The schemes could be divided into "character-based control schemes", where the player is controlling a main character (usually with an inventory system), e.g. Factorio, Satisfactory, Dyson Sphere Program and "god-mode-based control schemes" where there is no player character, e.g. Age of Empires 4, Settlers 3, etc.

We should look at both mouse & keyboard based controls as well as controller controls.
Stellar controller support could be a nice selling feature for our game, as it is usually an afterthought for this genre and not a great experience.
With the Steam Deck, controller support for PC games has become even more important.

**Comment by alice-i-cecile** [comment]
Agreed, I think this is a great lens to look at a critical problem.

**Comment by alice-i-cecile** [comment]
> How mouse interaction works in Civ 6:
> Less detail: https://discord.com/channels/1027393534627692645/1028004706435485766/1059197231393157171
>More detail: https://discord.com/channels/1027393534627692645/1028004706435485766/1059203882569449482

> traditional RTS: https://discord.com/channels/1027393534627692645/1028004706435485766/1059195353875894313

> Factorio: https://discord.com/channels/1027393534627692645/1028004706435485766/1058949910889779243


From @bzm3r

**Comment by bzm3r** [comment]
Some discussion around reasons to prefer drag-to-pan instead of pan-when-cursor-is-at-edge: https://discord.com/channels/1027393534627692645/1027394523585839165/1059331741694824449

**Comment by alice-i-cecile** [comment]
Closing, as I don't think that this analysis is a useful enough use of time at this stage :)
