### ISSUE TITLE
Making drag-to-pan-work

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#182]
The exact input combinations to trigger drag-to-pan are still up in the air, but for now assume we want LMB click + drag. 

Most recent work-in-progress along this line is in the [`broken-drag-to-pan`](https://github.com/Leafwing-Studios/Emergence/tree/broken-drag-to-pan) branch.

I think the issue is with how a click + drag is encoded: https://github.com/Leafwing-Studios/Emergence/blob/16838c988fcbfb09c3bfbdc6ac8af59c26868c49/emergence_lib/src/camera.rs#L54-L62

This *might* require an issue upstream in LWIM, but I am not yet sure.

**Comment by alice-i-cecile** [comment]
Rejected: this was concluded to be an anti-feature for experienced genre players.
