### ISSUE TITLE
Add "noob-trap" to Glossary 

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#183]
Possible definition:

> Features which exist in a game, but are anti-useful to use. Using them either only harms the player, or develops usage habits which are counter-productive. 

We *might* want to provide alternative words for use.

**Comment by alice-i-cecile** [comment]
> Features that seem helpful or appealing to beginners, but actually aren't. Using them is less effective in almost every circumstance than an alternative, or develops bad habits.
