### ISSUE TITLE
Discretizing Emergence

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#190]
Consensus around the channel is that we want to discretize various bits of Emergence for the sake of approachability. This is a tracking issue for these points. 

- [ ]  Time: #191 
- [ ]  Structure Mass: #192 and #212

**Comment by alice-i-cecile** [comment]
I'm not sure that signals need to be discretized? I suspect that as long as players can see the gradients we should be fine.

**Comment by alice-i-cecile** [comment]
This has mostly been done, closing and leaving #191 open.
