### ISSUE TITLE
Remove allowed duplicate dependencies caused by `bevy_egui`

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#194]
`bevy_egui` uses an old version of `arboard`, which causes many duplicate dependencies.
They are currently explicitly allowed in `deny.toml` so that we can start using `cargo-deny`.
Once the `arboard` dependency has been upgraded, we should try to update and remove the allowed entries once they are not applicable anymore.

**Comment by alice-i-cecile** [comment]
Fixed.
