### ISSUE TITLE
Add 3D graphics prototype

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#195]
Add a prototype for 3D graphics with a fixed camera angle.
It should be able to generate the hex tile map and encode the same information as the current 2D version.
It doesn't have to be pretty yet.

A good starting point for the hex tiles is probably this Bevy PR: <https://github.com/bevyengine/bevy/pull/6809>
Hexagons can be created with a cylinder with a resolution of 6.
I think this code is only available on `main` yet, but we can probably vendor it for now.

**Comment by alice-i-cecile** [comment]
Done.
