### ISSUE TITLE
Use new type for hex tile positions

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#206]
We currently use `TilePos` from `bevy_ecs_tilemap` for positions on the hex map.
Since we might want move to 3D graphics at some point or we might need custom code for the positions (e.g. conversions to different coordinate spaces), we should use a custom type instead.

The conversion to `TilePos` can then be done with a `From` implementation.

**Comment by alice-i-cecile** [comment]
Done!
