### ISSUE TITLE
Remove dependency on `bevy_ecs_tilemap` and work directly with a stripped down version that is focused on 2.5 D Hexes

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#213]
Concerns: 

* we want to use animated 3D meshes for tiles, something that bevy_ecs_tilemap doesn't quite support yet (even in the isometric 3D WIP code StarToaster shared with me)

* we can make the bevy_ecs_tilemap code much simpler by stripping out all the bits that are irrelevant to us, and focusing on what it is we need for Emergence; currently, it can be quite tough to continue adding to `bevy_ecs_tilemap` while keeping things general enough for everyone else's projects too

* once our own design is more fleshed out, we can contribute back to `bevy_ecs_tilemap`

**Comment by bzm3r** [comment]
A relevant FFF post: https://www.factorio.com/blog/post/fff-146

**Comment by bzm3r** [comment]
Another one: https://www.factorio.com/blog/post/fff-281

**Comment by alice-i-cecile** [comment]
Done!
