### ISSUE TITLE
Add simple gamepad support

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#214]
If we want to take gamepad support seriously, we should add it early and continously test it to make sure that all important workflows work well.

Adding the support late in the development process requires a lot more work and pain (see for example Factorio).

**Comment by bzm3r** [comment]
What are the pros/cons of gamepads?

**Comment by alice-i-cecile** [comment]
Main pros are:
- Steam deck support
- accessibility for physically disabled players

Cons:
- requires design and continual testing
- may limit complexity of game UI

This was also push us to contribute to efforts upstream to get better bevy_ui gamepad integration.

**Comment by bzm3r** [comment]
@alice-i-cecile You had me at accessibility.
