### ISSUE TITLE
Infopanel does not show hovered tile

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/Emergence#225]
Added in #204. All I see (on PopOS) is an empty box:

![image](https://user-images.githubusercontent.com/3579909/212492578-83497456-78ca-41d4-92fc-ada40b571df4.png)

**Comment by alice-i-cecile** [comment]
Okay, still broken for me on #204, so there's clearly something hardware or driver specific going on here...

I wonder if I have the font files?

**Comment by alice-i-cecile** [comment]
Okay, tile position is being detected and updated correctly 🤔

**Comment by TimJentzsch** [comment]
I'm also on Pop!_OS and I can't reproduce on `main`

**Comment by TimJentzsch** [comment]
Try pulling the LFS again, it uses a new font that I think is saved in there

**Comment by alice-i-cecile** [comment]
Yep, new font needed to be pulled with `git lfs pull`.
