### ISSUE TITLE
Controlling width of selection can be fiddly

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/Emergence#295]
Consider binding increase / decrease width to mouse wheel.

**Comment by alice-i-cecile** [comment]
Probably remove Control (area) selection entirely in favor of this.

**Comment by alice-i-cecile** [comment]
Hmm, but we can't use the mousewheel since that's bound to zoom 🤔 Could use Control + Mousewheel?

**Comment by TimJentzsch** [comment]
> Could use Control + Mousewheel?

Shift + Mousewheel or Ctrl + Mousewheel is sometimes used by digital painting tools to control the brush size. So I think it could work.

However, we will also need to think about (alternative) controls that work on keyboard only for accessibility, and the controller controls for Steam Deack & co.
