### ISSUE TITLE
Tile selection center feels oddly placed

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/Emergence#309]
Not at all convinced with the algorithm used to compute the center: definitely feels wrong.

See discussion and methods added in https://github.com/ManevilleF/hexx/issues/17

**Comment by alice-i-cecile** [comment]
I think that you have to compute the center using cubic coordinates, in some form or another. Results currently feel very arbitrary.

**Comment by alice-i-cecile** [comment]
Center does not need to contain an item from the selection.

**Comment by ManevilleF** [comment]
Did hexx 0.4 fix this ? The `center` algorithm was improved
