### ISSUE TITLE
Smoother height differences between hexes

### ISSUE THREAD

**Issue by plof27** [Leafwing-Studios/Emergence#347]
@alice-i-cecile and I were talking about the difficulties of unit animations across heights, and how we probably want to switch from "noisy heights" to more smooth hills. This got me thinking about how best to show and make use of that kind of terrain.

## Proposal
I believe it is desirable to "smooth out" the terrain. Instead of the "basalt columns" approach, it would look more like natural hills and cliffs, but with a hex grid projected onto the floor plane.

Benefits:
- More natural look and feel, more evocative of the natural environments we want the player to be thinking of
- Makes walking animations for units much easier to build
- Prevents issues of structures and units being hidden behind ledges
- Allows for more interesting gameplay hooks with slopes and drop offs
- More unique visuals (yay marketing)

Drawbacks:
- Mesh batching will be more challenging
- Rendering, in general, will be more challenging
- Both buildings and units will need to look good on sloped surfaces, including potentially compound curvature
- Understanding precise heights will be more challenging
- There are some constraints on world generation. For example, single tile peaks will have a sharp top instead of a smooth one.

## Implementation
- Every tile still has a single height, which is the height of the center of the tile
- Tile meshes are constructed now of 6 triangles for their "floor surface" (one for each wedge)
- Triangles angle their circumference corners based on the heights of their neighbors
  - Consider a hex corner, *C*. Observe that it has three neighbors
  - Note that any three points can uniquely identify a plane
  - Construct the plane defined by the three heights of the three tiles which meet at *C*.
  - Project *C*'s x,y coordinates onto this plane to determine its height
- All these possible floor triangles can be enumerated and batched, as long as:
  - Tile heights are discretion (likely desirable for gameplay reasons anyway)
  - The number of distinct height differences is finite and relatively small
- Define a height difference threshold (say, 3 units). Any height difference between tiles which is greater than this threshold uses a vertical wall, with some optional bending at the corners for visuals

**Comment by TimJentzsch** [comment]
This kind of reminds me of Settler III, which had a tile grid, but which was only visible while building. Otherwise the terrain was smoothed out:
![Settler 3 tiles when building](https://user-images.githubusercontent.com/13908946/218967542-e4a7e2dc-6768-4d02-a5f9-7c34c55018f4.png)

But they had much smaller tiles than we have right now.
That's probably also a parameter we can look at in more detail: The tile size / radius.

**Comment by alice-i-cecile** [comment]
I'm quite happy with the current look: unless we get stuck on unit animation this is a "won't fix".
