### ISSUE TITLE
Waste items should do... something?

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/Emergence#366]
When structures are deleted, units die or recipes are swapped, the waste items should not be lost to the void.

Our options:
1. Add them to a central store (Against the Storm, classic RTS). Doesn't work: there is no central store.
2. Add them to the player's inventory (Factorio). Doesn't work: we have no player.
3. Scatter them widely on the ground (Factorio inventory overflow). Fairly promising...
4. Create an infinitely large waste pile (Timberborn). Quite promising, but doesn't work for changing recipes.

**Comment by wallamide** [comment]
I like the idea of using 3, where we have them stay on the ground. We can encourage removing the waste by making the land it occupies unusable for a certain number of ticks/a time scale. Leafcutters have a whole system set up for waste disposal, as their fungal agrarian lifestyle requires them to be for their food supply: competing decomposers/virulent microbes pose an existential threat for fungi and thus the ants. 

Maybe we can take the idea of having a type of worker ant dedicated to this work. I believe IRL they have the older ants manage waste as the waste poses a potential health risk to the ants carrying out the job and so it keeps younger workers able to stay healthy and able to move the food/build things without scumming to illness; this seems like it could be a good system, but we would need to implement ant reproduction and aging for this to work. 

For a prototype, maybe waste becomes something that an ant has a low chance of choosing to pick up and take to a waste location?

**Comment by alice-i-cecile** [comment]
Yeah, 3 is my preference too. Thinking about how to depict that though. Do we show it as small items on the same tile? Can we show the waste level as a property of the tile?
