### ISSUE TITLE
Move graphics to their own crate

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#386]
The graphics module/plugin should be moved to its own crate (in the same repository).

This can improve compile times, but also ensures that we keep rendering logic separated from gameplay logic.
This will be very useful for headless testing later on.

It will also make it easier to switch out the visuals of the game later if needed.

**Comment by alice-i-cecile** [comment]
I'm increasingly nervous about this as I build out more. The "add meshes later" approach has an O(n) cost each frame that I'm not sure will remain trivial.

**Comment by TimJentzsch** [comment]
Hmmm, maybe some caching approach would work, but I guess it would be more natural and easy to reason about to store them directly in the same entity

**Comment by alice-i-cecile** [comment]
Closing in favor of #450.
