### ISSUE TITLE
Add the ability to select tiles

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/Emergence#49]
Follow-up to #3. Players should be able to:

- [ ] select tile groups of arbitrary shapes
- [ ] add and remove tiles to the selection using Shift + LMB
- [ ] select which area selection mode they want to use from a menu

When the player holds down LMB and drags from the originating tile, the area tool should be used.
There are several area tools to begin with:
- [ ] line
- [ ] freeform
- [ ] triangle
- [ ] expanding hexagon (from central tile)

**Comment by TimJentzsch** [comment]
I split this into several smaller, more actionable issues: #207, #208, #209.
