### ISSUE TITLE
Smoother camera controls

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/Emergence#543]
The camera controls with WASD currently feel very choppy.

Instead of moving the camera a fixed amount of units when the keys are pressed, the camera should have a bit of acceleration when the key is first pressed before the maximum movement speed is reached and a bit of an inertial movement once the key has been released.
This can make the camera feel a lot smoother and more natural.

The parameters to control the acceleration and inertia should be easy to tweak such that we can adjust them for optimal UX later on.

**Comment by alice-i-cecile** [comment]
We already have acceleration and such for camera speed: https://github.com/Leafwing-Studios/Emergence/blob/9546c258a07af5aa7088174d995b1c8155b17121/emergence_lib/src/player_interaction/camera.rs#L108

However, it *is* still too choppy. I think there are two problems there:

1. This hasn't been tuned well.
2. Frame rate is inconsistent: we should be using bevy_mod_framepace (#490) .

**Comment by TimJentzsch** [comment]
I don't think framerate should be an issue if we multiply the acceleration/velocity with the delta time
