### ISSUE TITLE
Cleaning up signals.

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#75]
We'll be having a `DashMap` of possible signals at each tile. Each signal has an `Emitter` id. An `Emitter` is, essentially, a `u16`. Each `Emitter` id also has some configuration information (diffusion rate, decay rate) and color information (specifying how it should be displayed as a map overlay) stored in a `HashMap`. 

This raises the question: suppose a large number of signals were created; but they have now decayed/are not being used anymore. There will be a large amount of unnecessary data auxiliary data in the game now. It should probably be cleaned up.

Likely, for unused signals, we will want to:

* save the configuration/colour information to disk on "signal cleanup", and then reload this information when the signals are in use again

* delete entries in the tile `DashMap`s related to unused signals

We will also want a good way to keep track of which signals need cleaning up. To figure out if a signal needs to be cleaned up, we need to know that it is at `0.0` at all tiles.

**Comment by alice-i-cecile** [comment]
Closing; pathfinding is getting reworked.
