### ISSUE TITLE
Add a `choose_max` pheromone transducer option for ants.

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#80]
Currently, ants probabilistically follow a signal up a gradient (see: https://github.com/Leafwing-Studios/Emergence/blob/8e3cbcaaf31544ad678f333d1d86ed6b685e52f3/emergence_lib/src/organisms/units.rs#L166). As the signal diffuses, their wandering becomes less effective towards the source of the signal. When the signal they are following is a pheromone, this leads to non-ideal behaviour, as it seems the ants are "not really following" the signal. It could be frustrating to the player.

Ants use a signal transducer to map an input signal into an output pathfinding weight (the higher the weight, the more likely it is the ants will move to that tile). 

When this signal is a pheromone, ants should (have the option) a transducer that assigns weight 1.0 to the neighbouring tile with the highest pheromone signal value out of all neighbours, and assign weight 0.0 to all tiles that do not have the highest pheromone signal value. If all tiles have the same pheromone signal value (unlikely, as we are using floating point numbers), we should weigh them all equally with 1.0.

**Comment by alice-i-cecile** [comment]
Closing for now: pathfinding is getting reworked.
