### ISSUE TITLE
Implement placeholder-ish `Food` and `Product` items.

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/Emergence#83]
`Plant`s produce `Food`.

`Ant`s carry `Food` to `Fungi`.

`Fungi` produce `Product`. 

Ants carry `Product` to `Plant` to help keep them alive. 

This simple system can be the skeleton used to implement the remaining points in: https://github.com/Leafwing-Studios/Emergence/issues/55

**Comment by alice-i-cecile** [comment]
Done.
